Check dependencies

diff --git a/depy b/depy
--- a/depy
+++ b/depy
@@ -27,6 +27,15 @@ function errorBig {
     announce $1 '0;30;41'
 }
 
+if ! which rsync >/dev/null; then
+    error "Cannot find rsync"
+    exit 1
+fi
+if ! which ssh >/dev/null; then
+    error "Cannot find ssh"
+    exit 1
+fi
+
 #
 # Validate Bash version
 #
